---------------------------------
-- BOTÓN RECOGER MESA
---------------------------------
-- INCLUDES
#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Zonas_Objetos/zonas_jugadores
#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Zonas_Objetos/zonas_GUID
#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Zonas_Objetos/contadores_GUID
#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Zonas_Objetos/objetos_GUID
#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Zonas_Objetos/textos_GUID

#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Funciones/recoger_mesa
#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Funciones/resetear_mesa

function onLoad()

  param = {
    label='RECOGER',
    click_function='pulsar_boton_recoger',
    function_owner=self,
    position={0,0.5,0},
    height=400,
    width=450,
    font_size=90,
    color={1,1,1},
    tooltip = 'Recoger mesa y resetear zonas',
  }

  self.createButton(param)
  self.setLock(true)

end

function pulsar_boton_recoger()
  --recoger_mesa()
  reset_table()
end