---------------------------------
-- BOTÓN CANASTA 01 - EQUIPO 01
---------------------------------

#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Funciones/funciones_boton
#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Zonas_Objetos/zonas_GUID
#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Zonas_Objetos/objetos_GUID
#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Zonas_Objetos/contadores_GUID
#include !/../../AppData/Local/Temp/TabletopSimulator/Tabletop Simulator Lua/Zonas_Objetos/textos_GUID

function onLoad()

  param = {
    label='CERRAR',
    click_function='pulsar_boton',
    function_owner=self,
    position={0,0.3,0},
    height=300,
    width=500,
    font_size=90,
    tooltip = 'Cerrar canasta',
  }

  self.createButton(param)
  self.setLock(true)

end

function pulsar_boton(obj, color)

  cond = detectar_jugador_que_pulsa(obj, color)

  if cond then
    agrupar_canasta(zonaCanastaE1_C01_GUID,1)
  end

end